---
- hosts: vinet
  remote_user: root
  roles:
    - { role: common, tags: ['common'] }
    - { role: sshd, tags: ['sshd'] }
    - { role: users, tags: ['users'] }
    - { role: sudo, tags: ['sudo', 'users'] }
    - { role: grsec, tags: ['grsec'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: mariadb, tags: ['mariadb'] }
    - { role: php-fpm, tags: ['php-fpm'] }
    - { role: forum, tags: ['forum'] }
